const problems = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    description: "Given an array of integers and a target, return the indices of the two numbers that add up to the target.",
    example: "nums = [2,7,11,15], target = 9 → Output: [0,1]",
    hint: "Try using a dictionary to store values you've seen.",
    answer_key: "seen[complement], i",
    starter: "def two_sum(nums, target):\n    # Write your solution here\n    pass",
  },
  {
    id: 2,
    title: "Reverse a String",
    difficulty: "Easy",
    description: "Write a function that takes a string and returns it reversed.",
    example: "Input: 'hello' → Output: 'olleh'",
    hint: "Python has a slicing trick for this!",
    answer_key: "[::-1]",
    starter: "def reverse_string(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 3,
    title: "FizzBuzz",
    difficulty: "Easy",
    description: "Write a function that returns 'Fizz' for multiples of 3, 'Buzz' for multiples of 5, and 'FizzBuzz' for multiples of both.",
    example: "Input: 15 → Output: 'FizzBuzz', Input: 3 → Output: 'Fizz'",
    hint: "Use the modulo operator % to check divisibility.",
    answer_key: "fizzbuzz",
    starter: "def fizzbuzz(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 4,
    title: "Palindrome Check",
    difficulty: "Easy",
    description: "Write a function that returns True if a string is a palindrome (reads the same forwards and backwards).",
    example: "Input: 'racecar' → Output: True, Input: 'hello' → Output: False",
    hint: "Compare the string with its reverse.",
    answer_key: "== s[::-1]",
    starter: "def is_palindrome(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 5,
    title: "Find Maximum",
    difficulty: "Easy",
    description: "Write a function that finds the maximum number in a list without using the built-in max() function.",
    example: "Input: [3, 1, 4, 1, 5, 9, 2] → Output: 9",
    hint: "Loop through the list keeping track of the largest number seen.",
    answer_key: "maximum =",
    starter: "def find_max(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 6,
    title: "Count Vowels",
    difficulty: "Easy",
    description: "Write a function that counts the number of vowels (a,e,i,o,u) in a given string.",
    example: "Input: 'hello world' → Output: 3",
    hint: "Loop through each character and check if it's in 'aeiou'.",
    answer_key: "in 'aeiou'",
    starter: "def count_vowels(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 7,
    title: "Sum of List",
    difficulty: "Easy",
    description: "Write a function that returns the sum of all numbers in a list without using the built-in sum() function.",
    example: "Input: [1, 2, 3, 4, 5] → Output: 15",
    hint: "Use a variable to keep a running total.",
    answer_key: "total +=",
    starter: "def sum_list(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 8,
    title: "Remove Duplicates",
    difficulty: "Medium",
    description: "Write a function that removes all duplicate values from a list and returns a list with only unique values.",
    example: "Input: [1, 2, 2, 3, 4, 4, 5] → Output: [1, 2, 3, 4, 5]",
    hint: "Sets only store unique values in Python.",
    answer_key: "set(",
    starter: "def remove_duplicates(nums):\n    # Write your solution here\n    pass",
  },
];

export default problems;