const problems = [

  // ── BEGINNER ──────────────────────────────────────────────────────────────
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    description: "Given an array of integers and a target, return the indices of the two numbers that add up to the target.",
    example: "nums = [2,7,11,15], target = 9 → Output: [0,1]",
    hint: "Try using a dictionary to store values you've seen.",
    answer_key: "seen[complement], i",
    starter: "def two_sum(nums, target):\n    # Write your solution here\n    pass",
  },
  {
    id: 2,
    title: "Reverse a String",
    difficulty: "Easy",
    description: "Write a function that takes a string and returns it reversed.",
    example: "Input: 'hello' → Output: 'olleh'",
    hint: "Python has a slicing trick for this!",
    answer_key: "[::-1]",
    starter: "def reverse_string(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 3,
    title: "FizzBuzz",
    difficulty: "Easy",
    description: "Write a function that returns 'Fizz' for multiples of 3, 'Buzz' for multiples of 5, and 'FizzBuzz' for multiples of both.",
    example: "Input: 15 → Output: 'FizzBuzz', Input: 3 → Output: 'Fizz'",
    hint: "Use the modulo operator % to check divisibility.",
    answer_key: "fizzbuzz",
    starter: "def fizzbuzz(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 4,
    title: "Palindrome Check",
    difficulty: "Easy",
    description: "Write a function that returns True if a string is a palindrome (reads the same forwards and backwards).",
    example: "Input: 'racecar' → Output: True, Input: 'hello' → Output: False",
    hint: "Compare the string with its reverse.",
    answer_key: "== s[::-1]",
    starter: "def is_palindrome(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 5,
    title: "Find Maximum",
    difficulty: "Easy",
    description: "Write a function that finds the maximum number in a list without using the built-in max() function.",
    example: "Input: [3, 1, 4, 1, 5, 9, 2] → Output: 9",
    hint: "Loop through the list keeping track of the largest number seen.",
    answer_key: "maximum =",
    starter: "def find_max(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 6,
    title: "Count Vowels",
    difficulty: "Easy",
    description: "Write a function that counts the number of vowels (a,e,i,o,u) in a given string.",
    example: "Input: 'hello world' → Output: 3",
    hint: "Loop through each character and check if it's in 'aeiou'.",
    answer_key: "aeiou",
    starter: "def count_vowels(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 7,
    title: "Sum of List",
    difficulty: "Easy",
    description: "Write a function that returns the sum of all numbers in a list without using the built-in sum() function.",
    example: "Input: [1, 2, 3, 4, 5] → Output: 15",
    hint: "Use a variable to keep a running total.",
    answer_key: "total +=",
    starter: "def sum_list(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 8,
    title: "Remove Duplicates",
    difficulty: "Medium",
    description: "Write a function that removes all duplicate values from a list and returns a list with only unique values.",
    example: "Input: [1, 2, 2, 3, 4, 4, 5] → Output: [1, 2, 3, 4, 5]",
    hint: "Sets only store unique values in Python.",
    answer_key: "set(",
    starter: "def remove_duplicates(nums):\n    # Write your solution here\n    pass",
  },

  // ── NEW BEGINNER ──────────────────────────────────────────────────────────
  {
    id: 9,
    title: "Even or Odd",
    difficulty: "Easy",
    description: "Write a function that returns 'Even' if a number is even and 'Odd' if it is odd.",
    example: "Input: 4 → Output: 'Even', Input: 7 → Output: 'Odd'",
    hint: "Use the modulo operator % to check if a number divides evenly by 2.",
    answer_key: "even",
    starter: "def even_or_odd(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 10,
    title: "Celsius to Fahrenheit",
    difficulty: "Easy",
    description: "Write a function that converts a temperature from Celsius to Fahrenheit.",
    example: "Input: 0 → Output: 32.0, Input: 100 → Output: 212.0",
    hint: "Formula: F = (C × 9/5) + 32",
    answer_key: "* 9/5",
    starter: "def celsius_to_fahrenheit(c):\n    # Write your solution here\n    pass",
  },
  {
    id: 11,
    title: "Count Words",
    difficulty: "Easy",
    description: "Write a function that counts the number of words in a sentence.",
    example: "Input: 'Hello world today' → Output: 3",
    hint: "Python strings have a split() method.",
    answer_key: "split()",
    starter: "def count_words(sentence):\n    # Write your solution here\n    pass",
  },
  {
    id: 12,
    title: "Square Numbers",
    difficulty: "Easy",
    description: "Write a function that takes a list of numbers and returns a new list with each number squared.",
    example: "Input: [1, 2, 3, 4] → Output: [1, 4, 9, 16]",
    hint: "Use a loop or list comprehension. num ** 2 squares a number.",
    answer_key: "** 2",
    starter: "def square_numbers(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 13,
    title: "Largest of Three",
    difficulty: "Easy",
    description: "Write a function that returns the largest of three numbers.",
    example: "Input: 3, 7, 5 → Output: 7",
    hint: "Use if/elif/else to compare the numbers.",
    answer_key: "return a",
    starter: "def largest_of_three(a, b, c):\n    # Write your solution here\n    pass",
  },
  {
    id: 14,
    title: "Reverse a List",
    difficulty: "Easy",
    description: "Write a function that takes a list and returns it in reversed order.",
    example: "Input: [1, 2, 3, 4, 5] → Output: [5, 4, 3, 2, 1]",
    hint: "Python lists support the same slicing as strings.",
    answer_key: "[::-1]",
    starter: "def reverse_list(lst):\n    # Write your solution here\n    pass",
  },
  {
    id: 15,
    title: "Factorial",
    difficulty: "Easy",
    description: "Write a function that returns the factorial of a number n (n! = n × (n-1) × ... × 1).",
    example: "Input: 5 → Output: 120, Input: 0 → Output: 1",
    hint: "Use a loop and multiply as you go. Remember 0! = 1.",
    answer_key: "result *=",
    starter: "def factorial(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 16,
    title: "Is Prime",
    difficulty: "Easy",
    description: "Write a function that returns True if a number is prime, False otherwise.",
    example: "Input: 7 → Output: True, Input: 4 → Output: False",
    hint: "A prime has no divisors other than 1 and itself. Check up to sqrt(n).",
    answer_key: "return False",
    starter: "def is_prime(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 17,
    title: "Sum of Digits",
    difficulty: "Easy",
    description: "Write a function that returns the sum of all digits of a number.",
    example: "Input: 1234 → Output: 10, Input: 9 → Output: 9",
    hint: "Convert the number to a string so you can loop over each digit.",
    answer_key: "int(d)",
    starter: "def sum_of_digits(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 18,
    title: "List Average",
    difficulty: "Easy",
    description: "Write a function that returns the average (mean) of a list of numbers.",
    example: "Input: [10, 20, 30] → Output: 20.0",
    hint: "Add all numbers together and divide by how many there are.",
    answer_key: "len(nums)",
    starter: "def list_average(nums):\n    # Write your solution here\n    pass",
  },

  // ── INTERMEDIATE ─────────────────────────────────────────────────────────
  {
    id: 19,
    title: "Anagram Check",
    difficulty: "Medium",
    description: "Write a function that returns True if two strings are anagrams of each other (same letters, different order).",
    example: "Input: 'listen', 'silent' → Output: True",
    hint: "Sort both strings and compare them.",
    answer_key: "sorted(",
    starter: "def is_anagram(s1, s2):\n    # Write your solution here\n    pass",
  },
  {
    id: 20,
    title: "Fibonacci Sequence",
    difficulty: "Medium",
    description: "Write a function that returns a list of the first n Fibonacci numbers.",
    example: "Input: 6 → Output: [0, 1, 1, 2, 3, 5]",
    hint: "Each number is the sum of the two before it. Start with [0, 1].",
    answer_key: "fib[-1] + fib[-2]",
    starter: "def fibonacci(n):\n    # Write your solution here\n    pass",
  },
  {
    id: 21,
    title: "Second Largest",
    difficulty: "Medium",
    description: "Write a function that returns the second largest number in a list.",
    example: "Input: [3, 1, 4, 1, 5, 9, 2, 6] → Output: 6",
    hint: "Sort the list and remove duplicates first.",
    answer_key: "sorted(",
    starter: "def second_largest(nums):\n    # Write your solution here\n    pass",
  },
  {
    id: 22,
    title: "Flatten a List",
    difficulty: "Medium",
    description: "Write a function that flattens a list of lists into a single list.",
    example: "Input: [[1,2],[3,4],[5]] → Output: [1, 2, 3, 4, 5]",
    hint: "Loop through each sub-list and extend a result list.",
    answer_key: "extend(",
    starter: "def flatten(lst):\n    # Write your solution here\n    pass",
  },
  {
    id: 23,
    title: "Word Frequency",
    difficulty: "Medium",
    description: "Write a function that returns a dictionary with the frequency of each word in a sentence.",
    example: "Input: 'the cat sat on the mat' → Output: {'the': 2, 'cat': 1, ...}",
    hint: "Use a dictionary and loop over the words.",
    answer_key: "freq[word]",
    starter: "def word_frequency(sentence):\n    # Write your solution here\n    pass",
  },
  {
    id: 24,
    title: "Missing Number",
    difficulty: "Medium",
    description: "Given a list of n-1 numbers taken from 1 to n, find the missing number.",
    example: "Input: [1, 2, 4, 5], n=5 → Output: 3",
    hint: "The sum of 1 to n is n*(n+1)//2. Subtract the list sum.",
    answer_key: "n*(n+1)",
    starter: "def missing_number(nums, n):\n    # Write your solution here\n    pass",
  },
  {
    id: 25,
    title: "Longest Word",
    difficulty: "Medium",
    description: "Write a function that returns the longest word in a sentence.",
    example: "Input: 'Python is awesome' → Output: 'awesome'",
    hint: "Split the sentence into words and find the one with the max length.",
    answer_key: "max(",
    starter: "def longest_word(sentence):\n    # Write your solution here\n    pass",
  },
  {
    id: 26,
    title: "Capitalize Words",
    difficulty: "Easy",
    description: "Write a function that capitalizes the first letter of every word in a sentence.",
    example: "Input: 'hello world' → Output: 'Hello World'",
    hint: "Python strings have a title() method, or you can split and capitalize each word.",
    answer_key: "title()",
    starter: "def capitalize_words(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 27,
    title: "Count Occurrences",
    difficulty: "Easy",
    description: "Write a function that counts how many times a specific element appears in a list.",
    example: "Input: [1, 2, 2, 3, 2], target=2 → Output: 3",
    hint: "Use the .count() method or a loop.",
    answer_key: "count(",
    starter: "def count_occurrences(lst, target):\n    # Write your solution here\n    pass",
  },
  {
    id: 28,
    title: "Power Function",
    difficulty: "Easy",
    description: "Write a function that returns base raised to the power of exponent without using the ** operator.",
    example: "Input: base=2, exp=10 → Output: 1024",
    hint: "Multiply base by itself exp times using a loop.",
    answer_key: "result *=",
    starter: "def power(base, exp):\n    # Write your solution here\n    pass",
  },

  // ── HARD ─────────────────────────────────────────────────────────────────
  {
    id: 29,
    title: "Balanced Brackets",
    difficulty: "Hard",
    description: "Write a function that returns True if the brackets in a string are balanced (every opening bracket has a matching closing bracket in correct order).",
    example: "Input: '({[]})' → Output: True, Input: '([)]' → Output: False",
    hint: "Use a stack. Push opening brackets, pop and check when you see a closing bracket.",
    answer_key: "stack",
    starter: "def is_balanced(s):\n    # Write your solution here\n    pass",
  },
  {
    id: 30,
    title: "Binary Search",
    difficulty: "Hard",
    description: "Implement binary search. Return the index of target in a sorted list, or -1 if not found.",
    example: "Input: nums=[1,3,5,7,9], target=7 → Output: 3",
    hint: "Keep track of left and right pointers. Check the middle element each time.",
    answer_key: "mid",
    starter: "def binary_search(nums, target):\n    # Write your solution here\n    pass",
  },
  {
    id: 31,
    title: "Longest Common Prefix",
    difficulty: "Hard",
    description: "Write a function that finds the longest common prefix string among a list of strings.",
    example: "Input: ['flower','flow','flight'] → Output: 'fl'",
    hint: "Sort the list. The common prefix of the first and last string is the answer.",
    answer_key: "prefix",
    starter: "def longest_common_prefix(strs):\n    # Write your solution here\n    pass",
  },
  {
    id: 32,
    title: "Group Anagrams",
    difficulty: "Hard",
    description: "Given a list of strings, group the anagrams together and return a list of groups.",
    example: "Input: ['eat','tea','tan','ate','nat','bat'] → Output: [['eat','tea','ate'],['tan','nat'],['bat']]",
    hint: "Sort each word to get its key. Words with the same sorted key are anagrams.",
    answer_key: "groups",
    starter: "def group_anagrams(strs):\n    # Write your solution here\n    pass",
  },
  {
    id: 33,
    title: "Rotate Matrix",
    difficulty: "Hard",
    description: "Write a function that rotates an n×n matrix 90 degrees clockwise in-place.",
    example: "Input: [[1,2],[3,4]] → Output: [[3,1],[4,2]]",
    hint: "First transpose the matrix (swap rows and columns), then reverse each row.",
    answer_key: "zip(",
    starter: "def rotate_matrix(matrix):\n    # Write your solution here\n    pass",
  },
  {
    id: 34,
    title: "Valid Sudoku Row",
    difficulty: "Hard",
    description: "Write a function that checks if a list of 9 numbers (1-9) is a valid Sudoku row (no duplicates, all numbers 1-9 present).",
    example: "Input: [5,3,4,6,7,8,9,1,2] → Output: True, Input: [5,5,4,6,7,8,9,1,2] → Output: False",
    hint: "Convert to a set and check its length equals 9, and all values are between 1 and 9.",
    answer_key: "set(",
    starter: "def valid_sudoku_row(row):\n    # Write your solution here\n    pass",
  },
];

export default problems;
